name: hd-poker-runs-nc
region: nyc1

services:
- name: web
  source_dir: /
  github:
    repo: lenorick22/hd-poker-runs-nc
    branch: main
  run_command: npm start
  build_command: npm run install:all && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "5000"
  - key: JWT_SECRET
    value: "${JWT_SECRET}"
    type: SECRET
  - key: MONGODB_URI
    value: "${MONGODB_URI}"
    type: SECRET
  - key: FRONTEND_URL
    value: "${_self.URL}"
  routes:
  - path: /
    preserve_path_prefix: false
